language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
notifications:
  slack: tbzsn:2OAGYmBzMMTEUIUjwKIHToRl
  email: false
before_install:
    composer self-update
install:
    composer install
before_script:
    - mysql -e 'create database tbzsn;'
script:
    - vendor/bin/phinx migrate -e travis
    - vendor/bin/phpcs --standard=phpcs.xml controllers/ models/
